# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2bcaf7ecdb8c17444459510d0126d3d23a74fcf2284280137f3ee9f588987c59b660c8b0d1cac598e571f3619d506dfb61679a2a01ca4f38c7b1a5076102252

test:
  secret_key_base: bac3e4a1fb532c25ba576b268646f758ef1e5d58e1f2d863d04025a6a2abcc24dd826e8e1d08ce76f307bffe2a07142989ab60eaa9cfc9ac0f1ce6fc7c10802c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
